apiVersion: zeabur.com/v1
kind: Template
metadata:
  name: NPVM
  description: Node Package Manager Visual Platform - A modern web UI for managing npm/yarn/pnpm/bun packages
  tags:
    - npm
    - package-manager
    - nodejs
    - developer-tools
  icon: https://raw.githubusercontent.com/h7ml/NPVM/main/packages/web/public/favicon.svg
spec:
  services:
    - name: npvm
      template: GIT
      source:
        repoURL: https://github.com/h7ml/NPVM
        branch: main
      build:
        buildCommand: pnpm install && pnpm build
        startCommand: node packages/server/dist/start.js
      ports:
        - port: 3456
          type: HTTP
      env:
        - name: NODE_ENV
          value: production
        - name: NPVM_DATA_DIR
          value: /app/data
      volumes:
        # 持久化全局包管理器缓存
        - name: npm-cache
          mountPath: /home/npvm/.npm
        - name: pnpm-store
          mountPath: /home/npvm/.pnpm-store
        - name: yarn-cache
          mountPath: /home/npvm/.yarn
        - name: bun-cache
          mountPath: /home/npvm/.bun
        # 持久化项目数据和 node_modules
        - name: project-data
          mountPath: /app/data
      resources:
        memory: 1024Mi
        cpu: 0.5
